PIM 955
pimlicolabs/erc20-paymaster pull request #30
Opened 2024-04-13 08:09 UTC by pavlovdog

2024-05-26 15:05 UTC, kristofgazso commented on src/oracles/TwapOracle.sol
> +        return (0, int256(price), 0, block.timestamp - 1, 0);
why -1

2024-05-26 15:06 UTC, kristofgazso commented on test/oracles/FixedOracle.t.sol
> +    function setUp() onFork(ForkNetwork.MAINNET, 19641719) external {
why fork instead of rebuilding state locally?

2024-05-26 15:06 UTC, kristofgazso commented on test/oracles/ManualOracle.t.sol
> +    function setUp() onFork(ForkNetwork.MAINNET, 19641719) external {
why fork instead of rebuilding state locally?

2024-05-26 15:06 UTC, kristofgazso commented on test/oracles/TwapOracle.t.sol
> +    function setUp() onFork(ForkNetwork.MAINNET, 19641719) external {}
why fork instead of rebuilding state locally?

2024-05-28 20:02 UTC, kristofgazso requested changes

2024-05-28 20:02 UTC, kristofgazso commented on src/factory/PimlicoFactory.sol
> +contract PimlicoFactory is FactoryPaymaster, FactoryOracle {
can we call it something other than Pimlico? it'd be nice to not include the name Pimlico in anything here

2024-05-29 10:48 UTC, mouseless-eth commented on src/ERC20PaymasterV06.sol
> +                getHash(userOp, uint48(bytes6(paymasterConfig[20:26])), uint48(bytes6(paymasterConfig[26:32])), 0),
I would parse out the paymaserConfig bytes into local variables instead of slicing to improve readability.

2024-05-29 10:48 UTC, mouseless-eth commented on src/factory/PaymasterFactory.sol
> +            keccak256(abi.encode(_version, constructorArgs)),
Not too important but could we allow for a salt param

2024-06-06 16:09 UTC, plusminushalf commented on src/ERC20PaymasterV07.sol
> +    function validatePaymasterUserOp(
This function can be moved to base right?

2024-07-16 14:44 UTC, merged